# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [4]:
print(np.version.version)

1.23.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [9]:
a = np.random.random((2, 3, 5))
print(a)

[[[0.04158328 0.30404209 0.17106994 0.18998219 0.36955459]
  [0.64140252 0.90548082 0.50345513 0.42331015 0.74620828]
  [0.14431975 0.83650979 0.47298933 0.65881336 0.17124676]]

 [[0.30192558 0.71593055 0.34564263 0.69102249 0.21554546]
  [0.17719755 0.728927   0.31074345 0.54561408 0.90974891]
  [0.83995398 0.18536752 0.74878488 0.61457956 0.98922504]]]


In [12]:
a = np.random.geometric(0.3, (2,3,5))
print(a)

[[[ 3  3  1  2  1]
  [ 1  1  1  4  3]
  [ 1  3  7  2  6]]

 [[ 3  7  1  1  7]
  [ 1  2  2  6 12]
  [ 1  5  4  3  2]]]


In [13]:
a = np.random.logistic(0, 1, (2,3,5))
print(a)

[[[-3.39054207  0.43902423  1.52290991 -1.66055984 -0.91817071]
  [ 2.08009951  1.0951844  -1.25396592  1.35300502  0.10886488]
  [-1.12054416 -1.39234901 -3.99443444  0.34428662 -1.00673482]]

 [[-0.59449958  2.02518581 -0.15572694 -3.6291939  -1.46467535]
  [-0.73100959  2.56401281  1.10001221  0.11469195  1.78917525]
  [ 0.44636799 -0.74415495 -0.48470735 -0.0181308  -1.16732593]]]


#### 4. Print *a*.


In [14]:
print(a)

[[[-3.39054207  0.43902423  1.52290991 -1.66055984 -0.91817071]
  [ 2.08009951  1.0951844  -1.25396592  1.35300502  0.10886488]
  [-1.12054416 -1.39234901 -3.99443444  0.34428662 -1.00673482]]

 [[-0.59449958  2.02518581 -0.15572694 -3.6291939  -1.46467535]
  [-0.73100959  2.56401281  1.10001221  0.11469195  1.78917525]
  [ 0.44636799 -0.74415495 -0.48470735 -0.0181308  -1.16732593]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [16]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
print(a.shape == b.shape)

False


#### 8. Are you able to add *a* and *b*? Why or why not?


In [18]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

Cannot add since they dont have the same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [31]:
c = np.transpose(b, (1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [32]:
d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [34]:
print(a)
print(d)

[[[-3.39054207  0.43902423  1.52290991 -1.66055984 -0.91817071]
  [ 2.08009951  1.0951844  -1.25396592  1.35300502  0.10886488]
  [-1.12054416 -1.39234901 -3.99443444  0.34428662 -1.00673482]]

 [[-0.59449958  2.02518581 -0.15572694 -3.6291939  -1.46467535]
  [-0.73100959  2.56401281  1.10001221  0.11469195  1.78917525]
  [ 0.44636799 -0.74415495 -0.48470735 -0.0181308  -1.16732593]]]
[[[-2.39054207  1.43902423  2.52290991 -0.66055984  0.08182929]
  [ 3.08009951  2.0951844  -0.25396592  2.35300502  1.10886488]
  [-0.12054416 -0.39234901 -2.99443444  1.34428662 -0.00673482]]

 [[ 0.40550042  3.02518581  0.84427306 -2.6291939  -0.46467535]
  [ 0.26899041  3.56401281  2.10001221  1.11469195  2.78917525]
  [ 1.44636799  0.25584505  0.51529265  0.9818692  -0.16732593]]]


d's elements are greater by 1 of a's

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [39]:
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [45]:
print(np.array_equal(a,e)) 

True


Yes, they are equal since each element is simply multiplied by 1

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [48]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

3.5640128097024437 -2.994434437430417 0.7085365071590068


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [66]:
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [73]:
import time

In [77]:
# start = time.time()
f = np.where(d > d_min, np.where(d < d_mean, 25, np.where(d == d_mean, 50, np.where(d < d_max, 75, 100))), 0)
# f
# for i in range(len(d)):
#     for j in range(len(d[0])):
#         for k in range(len(d[0,0])):
#             if d[i,j,k] == d_min:
#                 f[i,j,k] = 0
#             elif d[i,j,k] == d_max:
#                 f[i,j,k] = 100
#             elif d[i,j,k] == d_mean:
#                 f[i,j,k] = 50
#             elif d[i,j,k] < d_mean: 
#                 f[i,j,k] = 25
#             elif d[i,j,k] > d_mean: 
#                 f[i,j,k] = 75
# end = time.time()
print(f)
# print(end-start)

[[[ 25  75  75  25  25]
  [ 75  75  25  75  75]
  [ 25  25   0  75  25]]

 [[ 25  75  75  25  25]
  [ 25 100  75  75  75]
  [ 75  25  25  75  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [63]:
print(d_min, d_mean, d_max)
print(d)
print(f)

-2.994434437430417 0.7085365071590068 3.5640128097024437
[[[-2.39054207  1.43902423  2.52290991 -0.66055984  0.08182929]
  [ 3.08009951  2.0951844  -0.25396592  2.35300502  1.10886488]
  [-0.12054416 -0.39234901 -2.99443444  1.34428662 -0.00673482]]

 [[ 0.40550042  3.02518581  0.84427306 -2.6291939  -0.46467535]
  [ 0.26899041  3.56401281  2.10001221  1.11469195  2.78917525]
  [ 1.44636799  0.25584505  0.51529265  0.9818692  -0.16732593]]]
[[[ 25  75  75  25  25]
  [ 75  75  25  75  75]
  [ 25  25   0  75  25]]

 [[ 25  75  75  25  25]
  [ 25 100  75  75  75]
  [ 75  25  25  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [67]:
g = np.where(d > d_min, np.where(d < d_mean, "B", np.where(d == d_mean, "C", np.where(d < d_max, "D", "E"))), "A")
print(g)

[[['B' 'D' 'D' 'B' 'B']
  ['D' 'D' 'B' 'D' 'D']
  ['B' 'B' 'A' 'D' 'B']]

 [['B' 'D' 'D' 'B' 'B']
  ['B' 'E' 'D' 'D' 'D']
  ['D' 'B' 'B' 'D' 'B']]]
